### ISSUE TITLE
Constructing a tracer with a sample rate from JSON fails

### ISSUE THREAD

**Issue by pingles** [rnburn/zipkin-cpp-opentracing#24]
I'm in the process of updating the nginx opentracing module and noticed we had errors reporting that constructing a tracer was failing having updated to JSON.

I've just added a new test that fails: https://github.com/pingles/zipkin-cpp-opentracing/blob/master/zipkin_opentracing/test/ot_tracer_factory_test.cc#L34

I'm going to try and sort it asap but wanted to report here for visibility.

**Comment by rnburn** [comment]
Thanks for pointing it out.

Not sure if this is causing the problem, but noticed that there's a typo [here](https://github.com/pingles/zipkin-cpp-opentracing/blob/master/zipkin_opentracing/tracer_configuration.schema.json#L41) in the schema.

**Comment by pingles** [comment]
D’oh- totally missed that. I’ll give it a try in a bit! I wondered also if
it was a float/double conversion problem.

**Comment by pingles** [comment]
float isn't a valid type either, sorry: https://cswr.github.io/JsonSchema/spec/basic_types/
