### ISSUE TITLE
another error during compiling

### ISSUE THREAD

**Issue by ChangAlvin** [rnburn/zipkin-cpp-opentracing#32]
Scanning dependencies of target zipkin_opentracing
[ 54%] Building CXX object zipkin_opentracing/CMakeFiles/zipkin_opentracing.dir/src/utility.cc.o
[ 56%] Building CXX object zipkin_opentracing/CMakeFiles/zipkin_opentracing.dir/src/propagation.cc.o
[ 58%] Building CXX object zipkin_opentracing/CMakeFiles/zipkin_opentracing.dir/src/dynamic_load.cc.o
[ 60%] Building CXX object zipkin_opentracing/CMakeFiles/zipkin_opentracing.dir/src/tracer_factory.cc.o
[ 62%] Building CXX object zipkin_opentracing/CMakeFiles/zipkin_opentracing.dir/src/opentracing.cc.o
/wasHome/zipkin-cpp-opentracing-master/zipkin_opentracing/src/opentracing.cc:270:17: error: cannot declare field 鈠ipkin::OtSpan::span_context_?to be of abstract type 鈠ipkin::OtSpanContext?
   OtSpanContext span_context_;
                 ^
/wasHome/zipkin-cpp-opentracing-master/zipkin_opentracing/src/opentracing.cc:49:7: note:   because the following virtual functions are pure within 鈠ipkin::OtSpanContext?
 class OtSpanContext : public ot::SpanContext {
       ^
In file included from /usr/local/include/opentracing/tracer.h:5:0,
                 from /wasHome/zipkin-cpp-opentracing-master/zipkin_opentracing/include/zipkin/opentracing.h:1,
                 from /wasHome/zipkin-cpp-opentracing-master/zipkin_opentracing/src/opentracing.cc:2:
/usr/local/include/opentracing/span.h:34:40: note:      virtual std::unique_ptr<opentracing::v3_unstable::SpanContext> opentracing::v3_unstable::SpanContext::Clone() const
   virtual std::unique_ptr<SpanContext> Clone() const noexcept = 0;
                                        ^
/wasHome/zipkin-cpp-opentracing-master/zipkin_opentracing/src/opentracing.cc: In constructor 鈠ipkin::OtSpan::OtSpan(std::shared_ptr<const opentracing::v3_unstable::Tracer>&&, zipkin::SpanPtr&&, zipkin::Endpoin
t&&, const opentracing::v3_unstable::StartSpanOptions&)?
/wasHome/zipkin-cpp-opentracing-master/zipkin_opentracing/src/opentracing.cc:168:72: error: cannot allocate an object of abstract type 鈠ipkin::OtSpanContext?
           OtSpanContext{zipkin::SpanContext{*span_}, std::move(baggage)};
                                                                        ^
/wasHome/zipkin-cpp-opentracing-master/zipkin_opentracing/src/opentracing.cc:49:7: note:   since type 鈠ipkin::OtSpanContext?has pure virtual functions
 class OtSpanContext : public ot::SpanContext {
       ^
/wasHome/zipkin-cpp-opentracing-master/zipkin_opentracing/src/opentracing.cc:170:64: error: cannot allocate an object of abstract type 鈠ipkin::OtSpanContext?
       span_context_ = OtSpanContext{zipkin::SpanContext{*span_}};
                                                                ^
/wasHome/zipkin-cpp-opentracing-master/zipkin_opentracing/src/opentracing.cc:49:7: note:   since type 鈠ipkin::OtSpanContext?has pure virtual functions
 class OtSpanContext : public ot::SpanContext {
       ^
/wasHome/zipkin-cpp-opentracing-master/zipkin_opentracing/src/opentracing.cc: In instantiation of 鈕pentracing::v3_unstable::expected<std::unique_ptr<opentracing::v3_unstable::SpanContext> > zipkin::OtTracer::E
xtractImpl(Carrier&) const [with Carrier = std::basic_istream<char>]?
/wasHome/zipkin-cpp-opentracing-master/zipkin_opentracing/src/opentracing.cc:334:30:   required from here
/wasHome/zipkin-cpp-opentracing-master/zipkin_opentracing/src/opentracing.cc:380:75: error: cannot allocate an object of abstract type 鈠ipkin::OtSpanContext?
         std::move(zipkin_span_context_maybe->value()), std::move(baggage))};
                                                                           ^
/wasHome/zipkin-cpp-opentracing-master/zipkin_opentracing/src/opentracing.cc:49:7: note:   since type 鈠ipkin::OtSpanContext?has pure virtual functions
 class OtSpanContext : public ot::SpanContext {
       ^
/wasHome/zipkin-cpp-opentracing-master/zipkin_opentracing/src/opentracing.cc:380:75: error: no matching function for call to 鈙td::unique_ptr<opentracing::v3_unstable::SpanContext>::unique_ptr(<brace-enclosed i
nitializer list>)?
         std::move(zipkin_span_context_maybe->value()), std::move(baggage))};
                                                                           ^

**Comment by rnburn** [comment]
You need to compile against OT-1.5.1, not the master branch
