### ISSUE TITLE
opentracing: SpanContext data corrupted in Extract carrier

### ISSUE THREAD

**Issue by SDillibabu7** [rnburn/zipkin-cpp-opentracing#33]
I am facing this error, while executing the tutorial.cc code, 
Can someone help me here in this

Example error message: "opentracing: SpanContext data corrupted in Extract carrier"

Thanks,
Dilli Babu S

**Comment by rnburn** [comment]
It's meant to print that -- it's showing an example of how to do error handling

**Comment by SDillibabu7** [comment]
Hi, 
I understand that's an example of error handling. 
I am an new user, I am trying to start with this example program of tutorial.cc.

I am done with execution part, when I ran the code. I could get only the above example error message. Can You please elaborate or guide me to how to run this code. I wanted to see the output traces. Please, help me. Thanks

**Comment by SDillibabu7** [comment]
After running the program, the output is as like below. 

Can you please let me know, is there any problem here with the output.
How to get the 

Example error message: "opentracing: SpanContext data corrupted in Extract carrier"
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Notification: Gateway Timeout</title>
<style type="text/css">

</style>
</head>

<body>

<h1>This Page Cannot Be Displayed</h1>
<hr>

<p>
The system cannot communicate with the external server (&nbsp;1.1.1.1&nbsp;).
The Internet server may be busy, may be permanently down, or may be
unreachable because of network problems.
</p>

<p>
Please check the spelling of the Internet address entered.
If it is correct, try this request later.
</p>



<p>
If you have questions, or feel this is an error, please contact
your organization's network administrator
and provide the codes shown below.
</p>

<hr>
<table>
  <tr valign="top">
    <td valign="top" width="10%">Notification&nbsp;codes:&nbsp;</td>
    <td valign="top" class="code" width="90%">(1, GATEWAY_TIMEOUT, 1.1.1.1)</td>
  </tr>
</table>

</body>
</html>

Please, help me whether is correct or not. 
Thanks,
Dilli Babu S
