### ISSUE TITLE
[Feature request]: please update opentracing-cpp to 1.6.0

### ISSUE THREAD

**Issue by aledbf** [rnburn/zipkin-cpp-opentracing#39]

**Comment by smartnet-club** [comment]
error: field type 'zipkin::OtSpanContext' is an abstract class
opentracing-cpp/v1.6.0/include/opentracing/span.h:34:40: note: unimplemented pure virtual method 'Clone' in 'OtSpanContext'
  virtual std::unique_ptr<SpanContext> Clone() const noexcept = 0;

**Comment by aledbf** [comment]
@rnburn friendly ping

**Comment by aledbf** [comment]
@rnburn friendly ping
