### ISSUE TITLE
a build error

### ISSUE THREAD

**Issue by xiaoxiaolove** [rnburn/zipkin-cpp-opentracing#5]
zipkin-cpp-opentracing/zipkin_opentracing/src/opentracing.cc:28:51: error: converting to ‘std::tuple<std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >, std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > > >’ from initializer list would use explicit constructor constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >; _U2 = std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >; <template-parameter-2-3> = void; _T1 = std::chrono::time_point<std::chrono::_V2::system_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >; _T2 = std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long int, std::ratio<1l, 1000000000l> > >]’
     return {SystemClock::now(), SteadyClock::now()};

**Comment by rnburn** [comment]
Thanks. Not sure if you saw, but someone else was asking me about this today so I put in a change a couple of hours ago to fix it.
